// Run the built page's script against a stub DOM and report any error.
//
// The page is generated by string substitution into a template, so a patch
// that matches nothing fails silently while a neighbouring one applies --
// leaving code that references a variable never declared. That shipped once:
// every list on the page was empty because playerRow threw on its first call,
// and nothing in the Python test suite could see it.
//
// This does not check what the page looks like. It checks that the script runs
// to completion, which is the failure that turns the whole page blank.
//
//     node scripts/check_page.js [path/to/app.html]

const fs = require("fs");
const path = process.argv[2] || "data/app.html";

const html = fs.readFileSync(path, "utf8");
const script = html.split("<script>")[1]?.split("</script>")[0];
if (!script) {
  console.error("no <script> block found in " + path);
  process.exit(1);
}

// Enough of a DOM for the page to build its lists against.
const element = () => ({
  className: "", textContent: "", value: "", type: "", title: "",
  min: "", max: "", step: "", hidden: false,
  style: {}, dataset: {}, children: [],
  classList: { add() {}, remove() {}, toggle() {}, contains: () => false },
  append() {}, appendChild() {}, insertBefore() {}, remove() {},
  replaceChildren() {}, addEventListener() {}, focus() {},
  setAttribute() {}, getAttribute: () => null,
  querySelector: () => element(), querySelectorAll: () => [],
});

global.document = {
  createElement: element,
  createTextNode: (text) => ({ textContent: text }),
  getElementById: () => element(),
  querySelector: () => element(),
  querySelectorAll: () => [],
  documentElement: element(),
  body: element(),
  addEventListener() {},
};
global.window = {
  matchMedia: () => ({ matches: false, addEventListener() {} }),
  addEventListener() {},
};
global.setInterval = () => 0;
global.setTimeout = () => 0;

try {
  new Function(script)();
} catch (error) {
  console.error(`page script threw: ${error.constructor.name}: ${error.message}`);
  const frame = (error.stack || "").split("\n").find((l) => l.includes("<anonymous>"));
  if (frame) console.error("  " + frame.trim());
  process.exit(1);
}

console.log(`page script runs cleanly (${Math.round(script.length / 1024)} KB)`);
